config/routes.rb
Rails.application.routes.draw do

  resources :people do
    collection { post :import }
  end

  root 'welcome#show'
end

app/models/affiliation.rb
class Affiliation < ApplicationRecord
  has_many :people, through: :people_affiliations

  validates :name, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :people, through: :people_locations

  validates :name, presence: true
end

app/models/people_affiliation.rb
class PeopleAffiliation < ApplicationRecord
  belongs_to :person
  belongs_to :affiliation
end

app/models/people_location.rb
class PeopleLocation < ApplicationRecord
  belongs_to :person
  belongs_to :location
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :people_affiliations
  has_many :people_locations
  has_many :affiliations, through: :people_affiliations
  has_many :locations, through: :people_locations

  validates :first_name, presence: true
  validates :species, presence: true
  validates :gender, presence: true
  validates :weapon, presence: true
  validates :vehicle, presence: true

  def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|
      ActiveRecord::Base.transaction do
        name = row['Name']
        content = {}
        content[:first_name] = (name.split.count > 1 ? name.split[0..-2].join(' ') : name).capitalize
        content[:last_name]  = name.split.last.capitalize if name.split.count > 1
        content[:species]    = row['Species']
        content[:gender]     = row['Gender']
        content[:weapon]     = row['Weapon']
        content[:vehicle]    = row['Vehicle']
        person = new(content)
        next unless person.valid?
        person.save!

        locations = row['Location'].split(',')
        locations.each do |location|
          location = location.strip
          person.locations << Location.find_or_create_by(name: location.titleize)
        end
        next unless row['Affiliations'].present?
        affiliations = row['Affiliations'].split(',')
        affiliations.each do |affiliation|
          person.affiliations << Affiliation.find_or_create_by(name: affiliation.titleize)
        end
      end
    end
  end

  def self.search(search)
    joins(:locations, :affiliations)
      .select("locations.name, affiliations.name")
      .where(
        %{
          lower(locations.name) LIKE :search OR
          lower(affiliations.name) LIKE :search OR
          lower(people.first_name) LIKE :search OR
          lower(people.last_name) LIKE :search OR
          lower(people.species) LIKE :search OR
          lower(people.gender) LIKE :search OR
          lower(people.weapon) LIKE :search OR
          lower(people.vehicle) LIKE :search
        },
        search: "%#{sanitize_sql_like(search.try(:downcase))}%"
      ).uniq
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  helper_method :sort_column, :sort_direction

  def index
    @people = Person.includes(:affiliations, :locations)
                    .paginate(page: params[:page], per_page: 10)
                    .order(sort_column + " " + sort_direction)

    @people = @people.search(params[:search]) if params[:search].present?
  end

  def import
    Person.import(params[:file])
    redirect_to people_path, notice: "CSV imported"
  end

  private

  def sort_column
    Person.column_names.include?(params[:sort]) ? params[:sort] : "first_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column = nil, title)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, { sort: column, direction: direction }, { class: css_class }
  end
end

app/helpers/flashes_helper.rb
module FlashesHelper

  FLASH_CLASSES = { alert: 'danger', notice: 'success', warning: 'warning' }.freeze

  def flash_class(key)
    FLASH_CLASSES.fetch key.to_sym, key
  end

  def user_facing_flashes
    flash.to_hash.slice 'alert', 'notice', 'warning'
  end

end

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/common/_flashes.html.erb
<% if flash.any? %>
  <% user_facing_flashes.each do |key, value| %>
    <div class='alert alert-dismissable alert-<%= flash_class(key) %>'>
      <%= value %>
    </div>
  <% end %>
<% end %>

app/views/common/_navbar.html.erb
<nav class='navbar navbar-expand-lg navbar-dark bg-dark static-top' role='navigation'>
  <div class='container-fluid'>
    <div class='navbar-header'>
      <a class='navbar-brand' href='/'>CSV Uploader</a>
    </div>
    <div class='collapse navbar-collapse' id='bs-example-navbar-collapse-1'>
      <ul class='nav navbar-nav navbar-right'>
        <li>
          <%= link_to 'Upload CSV', new_person_path, class: 'nav-link' %>
        </li>
        <li>
          <%= link_to 'All Characters', people_path, class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CsvParser</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'common/navbar' %>
    <%= render 'common/flashes' %>
    <div class='container-fluid'>
      <%= yield %>
    </div>
  </body>
</html>

app/views/people/index.html.erb
<div class='col-md-12'>
  <br>
  <div class='col-md-4 float-right'>
    <div class='form-group'>
      <%= form_tag people_path, method: 'get', id: 'search-form', class: 'form-inline' do %>
        <%= search_field_tag :search, params[:search], class: 'form-control' %>
        <%= submit_tag 'Search', class: 'btn btn-info glyphicon glyphicon-search' %>
      <% end %>
    </div>
  </div>
  <table class='table table-hover'>
    <thead>
      <tr>
        <th><%= sortable 'first_name', 'First Name' %></th>
        <th><%= sortable 'last_name', 'Last Name' %></th>
        <th><%= sortable 'species', 'Species' %></th>
        <th><%= sortable 'gender', 'Gender' %></th>
        <th><%= sortable 'weapon', 'Weapon' %></th>
        <th><%= sortable 'vehicle', 'Vehicle' %></th>
        <th>Locations</th>
        <th>Affiliations</th>
      </tr>
    </thead>
    <tbody id='people-table'>
      <% @people.each do |person| %>
        <tr>
          <td><%= person.first_name %></td>
          <td><%= person.last_name %></td>
          <td><%= person.species %></td>
          <td><%= person.gender %></td>
          <td><%= person.weapon %></td>
          <td><%= person.vehicle %></td>
          <td><%= person.locations.pluck(:name).join(', ') %></td>
          <td><%= person.affiliations.pluck(:name).join(', ') %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

<script>
  $(document).ready(function(){
    $("#search").on("keyup", function() {
      var value = $(this).val().toLowerCase();
      $("#people-table tr").filter(function() {
        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
      });
    });
  });
</script>

app/views/people/new.html.erb
<div class='container'>
  <h1 class='mt-4'>Please upload your CSV</h1>
  <br>
  <div class = 'form-group'>
    <%= form_tag import_people_path, method: :post, multipart: true, class: 'form-inline' do %>
      <span class='btn btn-large btn-default'>
        <%= file_field_tag :file %>
      </span>
      <%= submit_tag 'Import', class: 'btn btn-submit btn-info' %>
    <% end %>
  </div>
</div>

app/views/welcome/show.html.erb
<div class='container'>
  <h1 class='mt-4'>Welcome to CSV Parser</h1>
</div>